version: "3"

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paysys
  web:
    build: .
    command: bash -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/opt/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

